# Generated by Django 4.0.3 on 2023-08-22 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbj', models.CharField(max_length=200)),
                ('con', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Aw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('qus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.qs')),
            ],
        ),
    ]
