# Generated by Django 4.0.3 on 2023-08-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aw',
            old_name='qus',
            new_name='qs',
        ),
    ]
